<a href="https://colab.research.google.com/github/JonyeokLEE/python_COLAB/blob/main/class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

class DataPreprocessing:
  def __init__(self, data, target):
    self.data=data
    self.target=target
    self.num_instances=self.data.shape[0]
    self.num_features=self.data.shape[1]
  def minmax(self):
    for i in range(self.num_features):
      col = self.data[:,i]
      self.data[:,i] = (self.data[:,i]-np.min(col))/(np.max(col)-np.min(col))
    return self
  def normalization(self):
    for i in range(self.num_features):
      col = self.data[:,i]
      mu, sigma = np.mean(col),np.std(col)
      self.data[:,i] = (self.data[:,i]-mu)/sigma
    return self
  def scaler(self, scaling=None):
    if scaling=='minmax':
      self.minmax()
    elif scaling=='standard':
      self.normalization
    else:
      pass
    return self.data

In [15]:
data=np.random.normal(0,10,(5,5))
target = np.random.normal(0,1,5)
print(data)

[[-29.00916959  12.20810361  -9.63161528  17.57301796   3.8634431 ]
 [ 11.40489106  -7.41959521   3.583076    12.68077222  -1.18186   ]
 [ -5.15249681  -1.41082479  -2.28454808   4.6229363   -6.64303742]
 [  2.04579794  -6.98394145 -15.26944959   0.63591416  -3.50060179]
 [ 11.95810079 -20.89313152   2.58619099  -2.09980803  -0.34794082]]


In [16]:
data_processor = DataPreprocessing(data,target)
data = data_processor.scaler('minmax')
print(data)

[[0.         1.         0.29904929 1.         1.        ]
 [0.9864963  0.40704029 1.         0.75131963 0.51979132]
 [0.58233494 0.58856736 0.68876191 0.34172743 0.        ]
 [0.75804337 0.42020154 0.         0.13906097 0.29909498]
 [1.         0.         0.94712194 0.         0.59916321]]


In [17]:
class DataPipeline(DataPreprocessing): #상속
  def __init__(self,data):
    self.data=data
    self.num_features=self.data.shape[1]
pipe = DataPipeline(data)
data = pipe.scaler("minmax")