<a href="https://colab.research.google.com/github/JonyeokLEE/python_COLAB/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [215]:
import numpy as np
a=np.array([1,5,0,-1]) #1차원
b=np.ones((2,2,2)) #모든 성분이 실수형 1, 2x2x2 3차원 배열
c=np.zeros((2,3)) #모든 성분이 실수형 0, 2x3 2차원 배열
d=np.arange(10) #0부터 9까지 10개의 실수가 나열된 1차원 배열
e=np.linspace(0,10,5) #0과 10을 양 끝 성분으로 취하고 배열의 크기가 5가 되게 하는 등차수열 성분을 나열한 1차원 배열
f=np.random.randint(2,10,5) #2 이상 10 미만의 정수 중 중복을 허용하여 5개를 뽑아 만든 1차원 배열

In [216]:
a

array([ 1,  5,  0, -1])

In [217]:
b

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [218]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [219]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
e

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [221]:
f

array([9, 5, 9, 7, 8])

In [222]:
c.shape #shape은 크기를 알 수 있음 -> c는 2X3

(2, 3)

In [223]:
len(c) #배열의 차원 중 첫번째 크기

2

In [224]:
c.ndim #배열의 차원을 나타냄. 즉, shape의 크기

2

In [225]:
c.dtype #배열 내 성분의 타입

dtype('float64')

In [226]:
c.reshape(1,6)

array([[0., 0., 0., 0., 0., 0.]])

In [227]:
#조건문을 이용한 인덱스 검색

mu = 0 #평균
sigma = 1 #표준편차
arr = np.random.normal(mu,sigma, (5,3)) #5X3 배열
arr
#평균 0, 표준편차 1인 정규분표를 따르는 5X3 배열

array([[ 1.24250517,  1.55631628, -0.43124295],
       [-0.58510308, -0.24215563,  0.67836305],
       [-0.37545391,  1.96053157,  0.15093129],
       [-0.87812019,  0.76222585,  1.09708446],
       [-0.37065689, -0.81726781,  0.59597412]])

In [228]:
np.where(abs(arr)>sigma, "out","in")
#해당 값의 절댓값이 표준편차보다 크면 out, 그렇지 않으면 in

array([['out', 'out', 'in'],
       ['in', 'in', 'in'],
       ['in', 'out', 'in'],
       ['in', 'in', 'out'],
       ['in', 'in', 'in']], dtype='<U3')

In [229]:
np.where(abs(arr)>sigma) #반환값을 설정하지 않으면 해당 인덱스를 산출

(array([0, 0, 2, 3]), array([0, 1, 1, 2]))

In [230]:
a= np.array([[1,3],[0,-1]])
b=np.random.randint(0,10,4).reshape(2,2)
a+b

array([[ 1, 12],
       [ 9,  2]])

In [231]:
a-b

array([[ 1, -6],
       [-9, -4]])

In [232]:
a*b

array([[ 0, 27],
       [ 0, -3]])

In [233]:
a**b

array([[    1, 19683],
       [    0,    -1]])

In [234]:
2*a

array([[ 2,  6],
       [ 0, -2]])

In [235]:
a-1

array([[ 0,  2],
       [-1, -2]])

In [236]:
np.matmul(a,b) #행렬 곱

array([[27, 18],
       [-9, -3]])

In [237]:
#concatenate 함수는 배열 병합 함수