<a href="https://colab.research.google.com/github/JonyeokLEE/python_COLAB/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
a=np.array([1,5,0,-1]) #1차원
b=np.ones((2,2,2)) #모든 성분이 실수형 1, 2x2x2 3차원 배열
c=np.zeros((2,3)) #모든 성분이 실수형 0, 2x3 2차원 배열
d=np.arange(10) #0부터 9까지 10개의 실수가 나열된 1차원 배열
e=np.linspace(0,10,5) #0과 10을 양 끝 성분으로 취하고 배열의 크기가 5가 되게 하는 등차수열 성분을 나열한 1차원 배열
f=np.random.randint(2,10,5) #2 이상 10 미만의 정수 중 중복을 허용하여 5개를 뽑아 만든 1차원 배열

In [38]:
a

array([ 1,  5,  0, -1])

In [39]:
b

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [40]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
e

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
f

array([4, 4, 9, 8, 8])

In [44]:
c.shape #shape은 크기를 알 수 있음 -> c는 2X3

(2, 3)

In [45]:
len(c) #배열의 차원 중 첫번째 크기

2

In [46]:
c.ndim #배열의 차원을 나타냄. 즉, shape의 크기

2

In [47]:
c.dtype #배열 내 성분의 타입

dtype('float64')