<a href="https://colab.research.google.com/github/JonyeokLEE/python_COLAB/blob/main/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [186]:
#Tensor는 Pytorch의 기본 단위, GPU 연산을 가능하게 하고, Numpy의 배열과 유사

import torch
import numpy as np

x = torch.empty(5,4)
print(x)

#크기가 5X4인 빈 tensor 생성, 초기화되지 않았으므로 할당된 메모리에 존재하는 값들이 초깃값

tensor([[7.3514e+17, 3.2675e-41, 1.7867e+14, 3.2675e-41],
        [1.4013e-43, 1.3312e-43, 5.6052e-44, 5.7453e-44],
        [6.4062e-41, 4.4842e-44, 6.4331e-41, 7.6573e-41],
        [6.9275e-41, 4.4842e-44, 9.1084e-44, 0.0000e+00],
        [6.7616e+17, 3.2675e-41, 6.7336e+17, 3.2675e-41]])


In [187]:
torch.ones(3,3) #1로 초기화 된 3X3 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [188]:
torch.zeros(2) #0으로 초기화 된 2행 배열

tensor([0., 0.])

In [189]:
torch.rand(5,6) #난수로 초기화 된 5X6 행렬

tensor([[0.0793, 0.2578, 0.9895, 0.1631, 0.3829, 0.6664],
        [0.5404, 0.3134, 0.4757, 0.4119, 0.9505, 0.8415],
        [0.4660, 0.7429, 0.8521, 0.1201, 0.5614, 0.1891],
        [0.5671, 0.1615, 0.2030, 0.2738, 0.3297, 0.3625],
        [0.2018, 0.8415, 0.6921, 0.5170, 0.2789, 0.6156]])

In [190]:
#리스트, 넘파이 배열을 텐서로 만들기
l = [13,4] #List
r = np.array([4,56,7]) #Numpy Array
torch.tensor(l)

tensor([13,  4])

In [191]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [192]:
x.size()

torch.Size([5, 4])

In [193]:
x.size()[1]

4

In [194]:
x.size(1)

4

In [195]:
type(x)

torch.Tensor

In [196]:
x=torch.rand(2,2)
y=torch.rand(2,2) #2X2 랜덤 행렬

x+y

tensor([[1.6526, 0.8373],
        [0.8719, 0.7771]])

In [197]:
torch.add(x,y)

tensor([[1.6526, 0.8373],
        [0.8719, 0.7771]])

In [198]:
y.add(x)

tensor([[1.6526, 0.8373],
        [0.8719, 0.7771]])

In [199]:
y.add_(x) #add()와 다르게 add_()는 더해서 y를 update
y

tensor([[1.6526, 0.8373],
        [0.8719, 0.7771]])

In [200]:
x=torch.rand(8,8)
x.size()

torch.Size([8, 8])

In [201]:
a=x.view(64) #8X8 -> 64
a.size()

torch.Size([64])

In [202]:
x.size()

torch.Size([8, 8])

In [203]:
b=x.view(-1,4,4) #-1은 원래 크기가 되게 하는 값 / 8X8 -> -1X4X4 = 4X4X4
b.size()

torch.Size([4, 4, 4])

In [204]:
x=torch.rand(8,8)
y=x.numpy()
type(y) #Tensor에서 Numpy Array로 변환

numpy.ndarray

In [205]:
x=torch.ones(1)
print(x.item())

#.item()은 손실 함숫값과 같이 숫자가 하나인 텐서를 텐서가 아닌 값으로 만들어준다.

1.0
