<a href="https://colab.research.google.com/github/JonyeokLEE/python_COLAB/blob/main/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#Tensor는 Pytorch의 기본 단위, GPU 연산을 가능하게 하고, Numpy의 배열과 유사

import torch
import numpy as np

x = torch.empty(5,4)
print(x)

#크기가 5X4인 빈 tensor 생성, 초기화되지 않았으므로 할당된 메모리에 존재하는 값들이 초깃값

tensor([[-9.6198e-04,  4.5502e-41,  1.3228e-08,  3.2908e-41],
        [ 1.4013e-45,  0.0000e+00,  1.3241e-08,  3.2908e-41],
        [ 1.4690e-08,  3.2908e-41,  0.0000e+00,  0.0000e+00],
        [ 1.4368e-08,  3.2908e-41,  1.4385e-09,  3.2908e-41],
        [-6.6309e+22,  4.5500e-41,  0.0000e+00,  0.0000e+00]])


In [17]:
torch.ones(3,3) #1로 초기화 된 3X3 행렬

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.zeros(2) #0으로 초기화 된 2행 배열

tensor([0., 0.])

In [19]:
torch.rand(5,6) #난수로 초기화 된 5X6 행렬

tensor([[0.0220, 0.8199, 0.9795, 0.8738, 0.5116, 0.0376],
        [0.1760, 0.7849, 0.1879, 0.6978, 0.1757, 0.1725],
        [0.6376, 0.1105, 0.5249, 0.1855, 0.7697, 0.1322],
        [0.4002, 0.2815, 0.5780, 0.6718, 0.9188, 0.6159],
        [0.9299, 0.5136, 0.6301, 0.5383, 0.5729, 0.2995]])

In [20]:
#리스트, 넘파이 배열을 텐서로 만들기
l = [13,4]
r = np.array([4,56,7])
torch.tensor(l)

tensor([13,  4])