<a href="https://colab.research.google.com/github/JonyeokLEE/python_COLAB/blob/main/randnum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf

rand = tf.random.uniform([1],0,1) #(shape(row,col), min_num, max_num)
print(rand)

tf.Tensor([0.57630444], shape=(1,), dtype=float32)


In [10]:
rand = tf.random.uniform([4],0,1) #(shape(row,col), min_num, max_num)
print(rand)

# uniform -> 균일분포: 최솟값과 최댓값 사이에서만 나옴
# normal -> 정규분포: 마치 시험 성적이나 키처럼 종형 곡선을 그리며 나타남

tf.Tensor([0.368052   0.14163017 0.9839088  0.3491888 ], shape=(4,), dtype=float32)


In [11]:
rand = tf.random.normal([4],0,1) #(shape(row,col), min_num, max_num)
print(rand)

tf.Tensor([-0.8477163  -0.4221131  -0.6844538   0.21724588], shape=(4,), dtype=float32)
